/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package toDoList;

import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void toDoTest() {
        ToDoList list = new ToDoList();
        ArrayList<String> comparator = new ArrayList<String>();
        comparator.add("Learn");
        comparator.add("Java");
        list.addToDos("Learn");
        list.addToDos("Java");
        assertEquals(comparator, list.listToDos());
    }
}

