/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wordGuessingGame;

import java.util.Scanner;

public class App {
    public static void main(String args[]) {
        WordChooser chooser = new WordChooser();
        Masker masker = new Masker();
        WordGuessingGame game = new WordGuessingGame(chooser,masker);
        System.out.println(masker.guessWord);
        while (game.getRemainingAttempts() > 0 && !game.isGameWon()){
            System.out.println(" Enter your guess:");
            Scanner userInput = new Scanner(System.in);
            Character guessAttempt = userInput.next().toUpperCase().charAt(0);
            game.guessLetter(guessAttempt);
            game.isGameWon();
            game.isGameLost();
        }
    }
}
